server:
  port: 8086
spring:
  profiles:
    active: native
  application:
    name: API-GATEWAY
  devtools:
    livereload:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: AUTH
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/**
        - id: STUDENT
          uri: lb://STUDENT
          predicates:
            - Path=/api/v1/student/**,
        - id: LECTURER
          uri: lb://LECTURER
          predicates:
            - Path=/api/v1/lecturer/**
        - id: KRS
          uri: lb://KRS
          predicates:
            - Path=/api/v1/student-record/**,/api/v1/student-records/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8085/eureka/
  instance:
    hostname: localhost